version: '3.8'

services:
  backend:
    build:
      context: ./backend-prueba-tareas
    container_name: laravel-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend-prueba-tareas:/var/www
    env_file:
      - .env.docker
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env.docker
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend-prueba-tareas
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-prueba-tareas:/app
    working_dir: /app
    command: npm run dev -- -H 0.0.0.0
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLL_INTERVAL=400
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql_data:
